project_id = "sjvmnfsdalwgvsqpzzze"

[functions.check-expiring-subscriptions]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.process-referral]
verify_jwt = true